---

- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: 192.168.0.44
  tasks:
    - name: Update Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
