---

- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: win2016.sharky.local
  transport: winrm
  tasks:
    - name: Update Windows
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
